[greeter]
theme-name=Arc-Dark
icon-theme-name=elementary
cursor-theme-name=elementary
indicators=~host;~spacer;~clock;~spacer;~session;~power
clock-format=%d %b, %H:%M
background=/usr/share/backgrounds/monody.svg
