title = "Monody Linux"
style = "kewt"
lang = "en"
logo = "logo.svg"
display_logo = false
display_title = true
logo_as_favicon = true
show_home_in_nav = false
footer = "Made by <a href=\"https://n0va.nekoweb.org\" target=\"_blank\">N0\\A</a>"
error_page = "not_found.html"
generate_page_title = true
versioning = true
enable_header_links = true
dir_indexes = true
posts_dir = "blog"